[build]
	publish = "_site"
	command = "npm run build"

[[plugins]]

	# Opt-in to the Netlify Lighthouse plugin (choose one):

	# 1. Go to your site on https://app.netlify.com and navigate to the Integrations tab, search for the `Lighthouse` plugin
	# 2. Or via `npm install -D @netlify/plugin-lighthouse`

	# Read more: https://github.com/netlify/netlify-plugin-lighthouse

	package = "@netlify/plugin-lighthouse"

	# optional, fails build when a category is below a threshold
	[plugins.inputs.thresholds]
		performance = 0.8
		accessibility = 0.8
		best-practices = 0.8
		seo = 0.8

	[plugins.inputs]
		output_path = "reports/lighthouse/index.html"

[build.processing]
	skip_processing = false

[[headers]]
	for = "**/*.stl"
	[headers.values]
		Content-Type = "application/sla"